# Generated by Django 2.1.3 on 2018-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300)),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('D', 'Dinner'), ('L', 'Lunch'), ('S', 'Snack'), ('DS', 'Dessert')], default='L', max_length=20)),
                ('instruction', models.TextField(blank=True)),
                ('wege', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
